[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
via_ir = true
optimizer = true
optimizer_runs = 1000
verbosity = 3

# Remappings for dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v4-core=lib/v4-core",
    "@uniswap/v4-periphery=lib/v4-periphery"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
